application: pure-advantage-691
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /images/(.*\.gif)
  mime_type: image/gif
  static_files: images/\1
  upload: (images/*\.gif)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.csv)
  mime_type: application/csv
  static_files: \1
  upload: (.*\.csv)

- url: /three-fonts/
  static_dir: three-fonts

- url: /getfile.php
  script: getfile.php

- url: /.*
  static_files: view.html
  upload: view.html
